
export const FETCH_CAT = 'FETCH_CAT'
export const FETCH_CAT_SUCCESS = 'FETCH_CAT_SUCCESS'
export const FETCH_CAT_FAILED = 'FETCH_CAT_FAILED'

export const ADD_CAT = 'ADD_CAT'
export const ADD_CAT_SUCCESS = 'ADD_CAT_SUCCESS'
export const ADD_CAT_FAILED = 'ADD_CAT_FAILED'

export const SET_CAT_EDITING = 'SET_CAT_EDITING'

export const UPDATE_CAT='UPDATE_CAT'
export const UPDATE_CAT_SUCCESS='UPDATE_CAT_SUCCESS'
export const UPDATE_CAT_FAILED='UPDATE_CAT_FAILED'

export const DELETE_CAT = 'DELETE_CAT'
export const DELETE_CAT_SUCCESS = 'DELETE_CAT_SUCCESS'
export const DELETE_CAT_FAILED = 'DELETE_CAT_FAILED'
