export const CHANGE_MODAL_CAT_TITLE = 'CHANGE_MODAL_CAT_TITLE'
export const CHANGE_MODAL_CAT_CONTENT = 'CHANGE_MODAL_CAT_CONTENT'
export const CHANGE_MODAL_CAT_BUTTON = 'CHANGE_MODAL_CAT_BUTTON'

export const SHOW_MODAL_CAT = 'SHOW_MODAL_CAT'
export const HIDE_MODAL_CAT = 'HIDE_MODAL_CAT'
export const TOGGLE_MODAL_CAT = 'TOGGLE_MODAL_CAT'